blank_issues_enabled: true
contact_links:
  - name: Self-serve Request
    url: https://github.com/filecoin-shipyard/github-mgmt/edit/master/github/filecoin-shipyard.yml
    about: Propose a GitHub configuration change by modifying filecoin-shipyard.yml
